apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: business-deployment
spec:
  selector:
    matchLabels:
      app: business
  # 3 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: business
    spec:
      containers:
      - name: nutrient-business
        image: suhdev/nutrient-business:latest
        env:
          - name: THIRD_PARTY_APP_KEY
            value: a960e49bac362a3797b16f81988201ba
          - name: THIRD_PARTY_APP_ID
            value: fc909774
        ports:
          - name: server
            containerPort: 8000
          - name: broker
            containerPort: 10000
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: business-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: server
      port: 8000
      targetPort: 8000
    - name: broker
      port: 10000
      targetPort: 10000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: business
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: ClusterIP