apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mariadb-deployment
spec:
  selector:
    matchLabels:
      app: mariadb
  # 3 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: mariadb
    spec:
      containers:
      - name: nutrient-mariadb
        image: mariadb:10.4
        env:
          - name: MYSQL_DATABASE
            value: "recipes"
          - name: MYSQL_ROOT_PASSWORD
            value: "1234"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: datastore-deployment
spec:
  selector:
    matchLabels:
      app: datastore
  # 3 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: datastore
    spec:
      containers:
      - name: nutrient-datastore
        image: suhdev/nutrient-datastore:latest
        ports:
          - containerPort: 8002
            name: server
          - containerPort: 10002
            name: broker
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: mariadb-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: conns
      port: 3306
      targetPort: 3306
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mariadb
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: datastore-service
spec:
  ports:
    # Accept traffic sent to port 80
    - name: server
      port: 8002
      targetPort: 8002
    - name: transport
      port: 10002
      targetPort: 10002
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: datastore
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: ClusterIP